server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/auth/ {
        proxy_pass http://wms-auth-api:3002/api/auth/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/locations {
        proxy_pass http://wms-master-data-api:3003/api/locations;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/products {
        proxy_pass http://wms-master-data-api:3003/api/products;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/stock {
        proxy_pass http://wms-inventory-api:3001/api/stock;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/report/inventory {
        proxy_pass http://wms-inventory-api:3001/api/report/inventory;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/report/locations {
        proxy_pass http://wms-master-data-api:3003/api/report/locations;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/report/products {
        proxy_pass http://wms-master-data-api:3003/api/report/products;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/receiving {
        proxy_pass http://wms-gr-api:3000/api/receiving;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/gr-plans {
        proxy_pass http://wms-gr-api:3000/api/gr-plans;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/suppliers {
        proxy_pass http://wms-master-data-api:3003/api/suppliers;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/customers {
        proxy_pass http://wms-master-data-api:3003/api/customers;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/warehouses {
        proxy_pass http://wms-master-data-api:3003/api/warehouses;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/outbound-plans {
        proxy_pass http://wms-outbound-api:3004/api/outbound-plans;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/picking {
        proxy_pass http://wms-outbound-api:3004/api/picking;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/shopee/ {
        proxy_pass http://wms-gr-api:3000/api/shopee/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
